#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

source ~/.homesick/repos/homeshick/homeshick.sh
source /usr/bin/tmuxp.zsh

export TERM=xterm-256color

export LC_ALL=en_US.UTF-8

export PYCHARM_JDK=/opt/java7/bin/java

# Alias mappings
#
alias pgstart="sudo systemctl start postgresql"
alias pgstop="sudo systemctl stop postgresql"
alias bc="bc -l"
alias homevpn="pushd ~/vpn_config/homevpn; sudo openvpn tmacey_asus.conf; popd"
#alias tmux="tmux -2"
#

. /usr/bin/virtualenvwrapper.sh
#. ~/.zprezto/modules/zaw/zaw.zsh
export PIP_REQUIRE_VIRTUALENV=true
export PIP_DOWNLOAD_CACHE=$HOME/.pip/cache

syspip(){
   PIP_REQUIRE_VIRTUALENV="" pip "$@"
}

pomo(){
work=${1:-25}
breaktime=${2:-5}
at now +$work minutes <<EOF
    notify-send -t $(($breaktime*600)) "<b style='font-size:60px;color:#FF0000;'>BREAK!</b><br>`date`"
EOF
}

source /usr/share/chruby/chruby.sh
source /usr/share/chruby/auto.sh
function gi() { curl -L -s https://www.gitignore.io/api/$@ ;}

export PATH="$HOME/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
pyenv virtualenvwrapper_lazy
