#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

source ~/.homesick/repos/homeshick/homeshick.sh
source /usr/bin/tmuxp.zsh

export TERM=xterm-256color

export LC_ALL=en_US.UTF-8


# Alias mappings
#
alias pgstart="sudo systemctl start postgresql"
alias pgstop="sudo systemctl stop postgresql"
alias bc="bc -l"
alias homevpn="pushd ~/vpn_config/homevpn; sudo openvpn tmacey_asus.conf; popd"
alias emacsclient="emacsclient -c"
alias emacs-shutdown="emacsclient -e '(kill-emacs)'"
#alias tmux="tmux -2"
#

#. /usr/bin/virtualenvwrapper.sh
#. ~/.zprezto/modules/zaw/zaw.zsh
export PIP_REQUIRE_VIRTUALENV=true

syspip(){
   PIP_REQUIRE_VIRTUALENV="" pip "$@"
}

syspip2(){
   PIP_REQUIRE_VIRTUALENV="" pip2 "$@"
}

source /usr/share/chruby/chruby.sh
source /usr/share/chruby/auto.sh

function gi() { curl -L -s https://www.gitignore.io/api/$@ ;}

export PATH="$HOME/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
pyenv virtualenvwrapper_lazy
source /usr/share/nvm/init-nvm.sh
