#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

source ~/.homesick/repos/homeshick/homeshick.sh
source /usr/bin/tmuxp.zsh
# . /usr/share/zsh/site-contrib/powerline.zsh

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting

export TERM=xterm-256color

export LC_ALL=en_US.UTF-8

export PYCHARM_JDK=/opt/java7/bin/java

# Alias mappings
#
alias pgstart="sudo systemctl start postgresql"
alias pgstop="sudo systemctl stop postgresql"
alias bc="bc -l"
#alias tmux="tmux -2"
#

export PIP_REQUIRE_VIRTUALENV=true
export PIP_DOWNLOAD_CACHE=$HOME/.pip/cache

syspip(){
   PIP_REQUIRE_VIRTUALENV="" pip "$@"
}
